### ISSUE TITLE
dji_flyc_param_ed.py

### ISSUE THREAD

**Issue by notsolowki** [mefistotelis/phantom-firmware-tools#11]
So this will read the structure array and export the parameters and variables?!?!

**Comment by mefistotelis** [comment]
Yes. I will soon make a description of it in README.

**Comment by notsolowki** [comment]
Do you know anything about whats going on right here.

**Comment by notsolowki** [comment]
WOW!. thankyou!!! when trying to repack it ends with

Traceback (most recent call last):
  File "dji_flyc_param_ed.py", line 413, in <module>
    main(sys.argv[1:])
  File "dji_flyc_param_ed.py", line 404, in main
    flyc_update(po,fwmdlfile)
  File "dji_flyc_param_ed.py", line 344, in flyc_update
    raise NotImplementedError('Function unfininshed.')
NotImplementedError: Function unfininshed.

**Comment by notsolowki** [comment]
Is it ready to use?!?!?

**Comment by MrBurnsAT** [comment]
I think it should work.

**Comment by notsolowki** [comment]
hey mrburns. im on 1.5+ right now. when i upgrade to 1.7 whats the story with the controller. will it need to be updated from 1.5.7 to 1.6 and if so whats the method of upgrading the controller only?!?

**Comment by notsolowki** [comment]
it works!!!!!!! holly s**** thank you soo much!!!@!@

**Comment by MrBurnsAT** [comment]
Mefistotelis is my Hero!!!!!!!


He is genius!!!!

**Comment by notsolowki** [comment]
I cant take all this excitement!@##!@

**Comment by chazzzzz** [comment]
Hey this is pretty cool. I think I found two things I'll try changing...I think the index 264 is when you get that annoying low battery warning and 256 is also as annoying, the 10% battery auto landing thing. Maybe I'll change them both to 0. What do you guys think?

"index" : 264,
		"typeID" : 0,
		"size" : 1,
		"attribute" : 11,
		"minValue" : 0,
		"maxValue" : 100,
		"defaultValue" : 15,
		"name" : "g_config.voltage2.level1_smart_battert_gohome_0",
		"modify" : true

"index" : 265,
		"typeID" : 0,
		"size" : 1,
		"attribute" : 11,
		"minValue" : 0,
		"maxValue" : 100,
		"defaultValue" : 10,
		"name" : "g_config.voltage2.level2_smart_battert_land_0",
		"modify" : true

any guesses what index 338 is??? Speed perhaps?
"index" : 338,
		"typeID" : 5,
		"size" : 2,
		"attribute" : 11,
		"minValue" : 0,
		"maxValue" : 100,
		"defaultValue" : 90,
		"name" : "g_config.control.throttle_output_max_0",
		"modify" : true

**Comment by mefistotelis** [comment]
For me the warnings is useful; but if you want it gone, I'd change it to 1% and 2% rather than 0 - it is safer not to use zeros in places where there were no zeros before.

Also, don't touch min and max values, change only the "default".

**Comment by chazzzzz** [comment]
Yeah I already did it...Default values yes, thanks...I figures as long as I stayed at the min value it would be okay...It did act a little differently during updating and took a long time, about 30 to 40 min...It's probably because it updates everything with that debug file, but it DID seem to take...The Dji go app still displays the normal values for these settings which I did expect...I will have to test it...Thanks bud...

**Comment by notsolowki** [comment]
changing the battery values have no effect.

**Comment by ferraript** [comment]
for clarification, has anybody had any success of changing any parameter, so it was effective?

**Comment by notsolowki** [comment]
Yea the height

**Comment by notsolowki** [comment]
if some tools ever turn up to pull the rest of the variables in the filght controller i have no problems testing them so descriptions can be made :)

**Comment by ferraript** [comment]
>changing the battery values have no effect

maybe AC is pulling those from battery

**Comment by notsolowki** [comment]
Hey mefistotelis, are you working on any more formware projects?

**Comment by mefistotelis** [comment]
> are you working on any more firmware projects?

Besides the Phantom tools? no.

**Comment by notsolowki** [comment]
Sorry, i mean and more firmware tools for phantom tools.

**Comment by notsolowki** [comment]
are you still working on the phantom firmware tools?

**Comment by notsolowki** [comment]
also i found if you tap flight controller in dji go under about, 12 times it gives you a uuid

**Comment by notsolowki** [comment]
i noticed that if you go to dji go and look at the gains under advanced settings, their values are 8-12-,100 default. if you go back one menu and retore default settings then 130 gets populated into the boxes. weird

**Comment by mefistotelis** [comment]
> are you still working on the phantom firmware tools?

I'm working on the remote controller fw.

There is also some work to do with firmwares support  - if you use test_all.sh, you'll notice that some tests fail. I'm not sure if II'll be working on that.

**Comment by notsolowki** [comment]
do you think the ESC firmware monitors the RPM of the motors. i Re-calibrated the RC but instead of pushing the sticks all the way i only pushed them to about 20 percent. when i restarted the motors and pushed the sticks all the way i got a maximum motor speed reached

**Comment by mefistotelis** [comment]
> do you think the ESC firmware monitors the RPM of the motors.

Of course it does.

ESC gets instructions from the flight controller; There is nothing interesting there for hacking. But it does contain some proprietary algorithms, ie. the active breaking implementation, which other companies (and open-source software) didn't had for many months after DJI released it. This is why ESC firmware is encrypted.

**Comment by notsolowki** [comment]
have you found anything in the RC firmware thats interesting.

**Comment by notsolowki** [comment]
i see alot of this in the app 


  Ldji/midware/data/model/P3/DataGimbalGetPushParams
  dji/midware/data/model/P3/DataGimbalGetPushParams 
   Ldji/midware/data/model/P3/DataRcGetPushParams
   dji/midware/data/model/P3/DataRcGetPushParams 
  Ldji/midware/data/model/P3/DataRcGetPushParams

**Comment by notsolowki** [comment]
Some how my controls ended up backwards,

**Comment by notsolowki** [comment]
the csc is up and left now

**Comment by mefistotelis** [comment]
> can you tell me how to use the test scripts i cant seem to figure out the cml

for test_all.sh - you just run it. The others are used within test_all.sh, so to just look inside to get it.

These shell scripts are usable in any bash-compatible shell; I'm using msys2 to run them on my Windows machine.

**Comment by notsolowki** [comment]
thankyou, can you tell me how can i downgrade my rc. some how i got the sticks screwed up and i think the firmware needs to be reflashed. i cant reset them ive tried everything i can think of

**Comment by notsolowki** [comment]
okay i dont understan. i reinstall the rc and the aircraft and the app and still my controls are backwards???

**Comment by ferraript** [comment]
another recalibration doesn't help?

**Comment by notsolowki** [comment]
nope

**Comment by MrBurnsAT** [comment]
Have u maybe Set custom Stick Mode???

**Comment by notsolowki** [comment]
no. i tried all modes. when i setup custom they were backwards too

**Comment by notsolowki** [comment]
this started when i installed dji go 2.4.2 and reset the default settings in the aircraft menu

**Comment by notsolowki** [comment]
@mefistotelis : can you shed some light on this maybe

**Comment by notsolowki** [comment]
i figured it out. i reinstalled the old app and upgraded my rc and ac. then in the old app i reset all to default. and all was back to normal. its weird. in dji go 2.4 if you hit reset it says its going to reset the flight controlelr parameters to default. if ou hit reset in the new dji go apk it says its going to reset the gain/expo....

**Comment by notsolowki** [comment]
it might have happened when i changed flyc_param_infos in the old app then hit restore default settings.

**Comment by ferraript** [comment]
there is reverse_input_0 in both DJI GO and AC firmware
maybe you had this set to wrong value

you can check it:
do a flight now, when you have controls right
then get the DAT flight logs, one from this last flight and one where the controls were reversed
then generate config file using DatCon and check that reverse_input_0 value

**Comment by notsolowki** [comment]
i compared the values edited with flyc_param_ed.py to the new binary generated and they seem to change successfully within the structure

**Comment by notsolowki** [comment]
i didnt upgrade past 1.7.6 that i was on. i upgraded the rc to 1.60 and the drone to 1.8. i noticed that when 1.8 is installed it updates alot differently

**Comment by notsolowki** [comment]
okay before all this happened , i flashed a modified binary with all the pantilt-"pitch" settings really low. but the dji go app 3.1.1 wouldnt let me set them any lower or higher still. but when i would hit restore default it would set them to 130, which is out of their range according to the app. and the 130 made a difference in the pitch gain because i could set it back to 120 and notice a difference. but now that i have a non-modified FW  setting them to default only sets them abck to 100.. weird?!?!?

**Comment by notsolowki** [comment]
When i tried to downgrade back to 1.7.60 after i had to update to 1.8 to fix my controls, it wouldnt talk to my rc. After i did the normal method to downgrade it said i was on 1.7.6+ and i got the no signal error. Then i tried to downgrade again to 1.6 but it wouldnt even start the process saying it cant be downgraded. Knowing this isnt true because ive done it 100 times. I decided to put the p3x_fw_debug on the sd card with 1.7.6 firmware file and started tge process. After it finished it said i was on 1.7.6 instead of 1.7.6+ and my controller issues went away

**Comment by notsolowki** [comment]
So dji go 2.4 updated some parameters in flyc when i did a default reset. It even says its going to reset the flight controller parameters when 3.1.1 says it will reset the gain/expo only

**Comment by notsolowki** [comment]
i figured out how to use the edited parameters

**Comment by notsolowki** [comment]
@mefistotelis I'm sorry, i should have said can you add the go home speed to flyc_param_ed.py? thankyou again!!

**Comment by ferraript** [comment]
>can you please add the go home speed to flyc_param_ed.py?

I don't think that's possible
1. flyc_param_ed extracts all params from firmware and as you can see, there is no such a parameter there
2. I believe that this parameter comes from battery, because in each of my flight logs I can see:
`155 [smart_battery]this fireware calc gohme speed:7.800000 - land speed:2.500000`

**Comment by mefistotelis** [comment]
Yes, flyc_param_ed extracts all parameters from the array.

**Comment by notsolowki** [comment]
the speed is not in the battery its in the flight controller binary. 
@mefistotelis is the go home speed in the array. i dont hink i seen it., but i did see it in the flight controller

**Comment by mefistotelis** [comment]
Ok, since you seem determined for this, I looked at the code.

Go home speed is hard-coded into firmware. It is hard to find all places which would have to be modified to change it. Definitely it appears at:
<pre>sub_80680F4, sub_8068294; used value:
.text:08068290 flt_8068290     DCFS 7.8
sub_8068F90; used value:
.text:08069068 dbl_8069068     DCFD 7.80000019
</pre>

To modify it, try changing these two values. If this won't help, you'll have to search further.

**Comment by ferraript** [comment]
in which module binary you found it, @mefistotelis , m0305 or m0306?

**Comment by mefistotelis** [comment]
We don't have unencrypted m0305. Also, it contains a loader, not a real flyc code. It would help in hacking encryption, but not in changing any parameters.

**Comment by notsolowki** [comment]
i wish i knew how to byte patch. do you know any easier way for us to do it?

**Comment by notsolowki** [comment]
how can i allign part of the instruction to the hex view in ida. say i highlight 7.8 and align it with hex view it selects a whole lot of data in hex view. how can i change the instruction and view what the changes would look like in hex view

**Comment by mefistotelis** [comment]
You can find the correct byte values in [any converted](http://lmgtfy.com/?q=float+to+hex+online).

At :08068290 you have float, at :08069068 there's double.

**Comment by notsolowki** [comment]
im going to make a list of know parameters, ill update this as i figure them out. if anyone know of any add them in a comment and ill add them to the list

"name" : "g_config.control.vert_up_vel_0" ascend speed
"name" : "g_config.control.vert_down_vel_0" descend speed
"name" : "g_config.engine.upper_bound_0" motor speed limit
"name" : "g_config.engine.idle_level_0" controls idle speed on ground
"name" : "g_config.flying_limit.max_height_0" controls maximum altitude 
"name" : "g_config.novice_cfg.max_height_0" maximum height in beginner mode

**Comment by mefistotelis** [comment]
Here's a little present - a command which changes the gohome speed value from 7.8 to 15.3:
<pre>xxd  -p -c16 P3X_FW_V01.07.0060_mi01.bin | \
  sed 's/\(9a99f940\)\(2de9f041\)/cdcc7441\2/' | \
  sed 's/0000004033331f40/9a99999999992e40/' | \
  xxd -r -p -c16 > P3X_FW_V01.07.0060_mi01-mod.bin</pre>

To verify which bytes were changes, you can use:
<pre>cmp -l P3X_FW_V01.07.0060_mi01-mod.bin P3X_FW_V01.07.0060_mi01.bin</pre>

**Comment by notsolowki** [comment]
WOW THANKYOU SOO MUCH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by notsolowki** [comment]
so then i assume this is the binary that is modified? P3X_FW_V01.07.0060_mi01-mod.bin

**Comment by notsolowki** [comment]
im not sure if it make changes in real flight but in the simulator its still only comes back at 24

**Comment by notsolowki** [comment]
lets make sure i did this right,
laptop@laptop-VPCEH14FM:~/Desktop/phantom-firmware-tools-master (2)$ xxd  -p -c16 P3X_FW_V01.07.0060_mi01.bin | \
>   sed 's/\(9a99f940\)\(2de9f041\)/cdcc7441\2/' | \
>   sed 's/0000004033331f40/9a99999999992e40/' | \
>   xxd -r -p -c16 > P3X_FW_V01.07.0060_mi01-mod.binlaptop@laptop-VPCEH14FM:~/Desktop/phantom-firmware-tools-master (2)$ cmp -l PMCAPPFw3.bin P3X_FW_V01.07.0060_mi01.bin
295569 315 232
295570 314 231
295571 164 371
295572 101 100
299113 232   0
299114 231   0
299115 231   0
299116 231 100
299117 231  63
299118 231  63
299119  56  37

**Comment by mefistotelis** [comment]
Well that would mean the value is hard-coded somewhere else as well; this may be hard to find.

**Comment by notsolowki** [comment]
i will say that sometimes it got up to 26. im pretty sure that it usually got u to 24 really slow

**Comment by chazzzzz** [comment]
Hey mefistotelis  i know you don't like to spoon feed instructions but can you make an exception this time? How do you run that command u have up there? I tried in Command Prompt and its not working for me...As notsolowki pointed out I'm a little slow with instructions...

**Comment by ferraript** [comment]
what command prompt?
those are unix commands

**Comment by notsolowki** [comment]
They were not effective anyways.

**Comment by notsolowki** [comment]
ferraript can you tell me what the go home speed string looks like in the config.txt log with an unmodified binary. do they misspell it gohme

**Comment by notsolowki** [comment]
so then the commands are not changing the right parameter?

**Comment by chazzzzz** [comment]
Oh ok i was trying to run it with the python file dji_flyc_param_ed.py in cmd prompt like i've BEEN doing...Not, not that i dont trust you but remember "trust but verify"...

**Comment by chazzzzz** [comment]
not,  you screwed me twice because i copied your shitty ass version! you missed a \ . I suck at typing and apparently ya can't copy and past on Bash! Oh and you also forgot this one 299119  56  37

**Comment by notsolowki** [comment]
what are you talking about

**Comment by notsolowki** [comment]
genius i didnt paste that as a command for people to use. you screwed your self by not know what you doing or talking about

**Comment by chazzzzz** [comment]
just like i said i was typing in your copy of the code in your post above instead of mefistotelis copy and you missed a \ . It took me twice of typing to notice that error.

mefistotelis = sed 's/\(9a
yours = sed 's/(9a

**Comment by notsolowki** [comment]
ahh. i thought you were talking about mefistotelis commands. thats oaky. if you brick your flight controller you can easily recover it. as long as you use that single module

**Comment by chazzzzz** [comment]
yeah i flashed about 30 times now and once i pulled the sd card out early for some reason, brain fart i guess, and i had to fix it with that... It beeped like it does on startup for about 10min while it flashed a clean copy...my woman was getin pissed she was trien to sleep :)

**Comment by notsolowki** [comment]
yea that sound is horrible

**Comment by notsolowki** [comment]
be careful with the parameters, some of them can cause instant takeoff without the controller being able to control it. always test in the simulator first. that fw i sent u a link to has everything pretty much maxed out

**Comment by notsolowki** [comment]
next the battery parameters need investigating. did you know the ios app has a freaking rpm guage

**Comment by chazzzzz** [comment]
yeah you had a good idea with the simulator its really the only way i could or will test before i actually fly...I set some parameters and in the sim it took off before i even hit the stick and kept going...no stopping that one..

.I have ios i didn't see the gauge...

This setting is of interest to me because its the same speed as RTH...But it doesn't do anything that i can tell...Or some limit needs to be turned up for this to work...Battery perhaps yes...But i always change the default for this one just in case

"index" : 314,
		"typeID" : 5,
		"size" : 2,
		"attribute" : 11,
		"minValue" : 10,
		"maxValue" : 60,
		"defaultValue" : 23,
		"name" : "g_config.control.horiz_vel_atti_range_0", 
		"modify" : true

**Comment by notsolowki** [comment]
yea thats the setting i said not to mess with

**Comment by notsolowki** [comment]
you might aswell save yourself the time and just use my fw container and use the app to send the settings

**Comment by notsolowki** [comment]
it will bring you to max speeds overall and still be pretty stable. i tested it all day trying to flip it out of the air.

**Comment by notsolowki** [comment]
2 hours of trying to flip it i got in 2 360's and it would flip and go right back to stable. thats if you go liek 60 mph and yawn then bank it. in gps mode its not possible

**Comment by chazzzzz** [comment]
Ha ha your a funny man :0)  Hows your smashed bird doin? I don't want your crazy speeds i'm lookin for constant and sable 42mph not speeds all over the board or i don't need to go up 60mph who cares about up i want to go out....The only thing i need now is rth speed and I'll be done..I'll change every setting in there to find it if i have too.

**Comment by notsolowki** [comment]
my "smashed bird" is doing fine. you dont know what your looking for because you have no idea what your doing. your lucky i helped you get this far

**Comment by notsolowki** [comment]
why do i sometimes get this error

Warning: multiple (2) matches found for parameters array with alignment 0x02

**Comment by mefistotelis** [comment]
It's best to look at the Python code and check what condition triggers the warning and what it means there.

**Comment by notsolowki** [comment]
so far it only happens when i change this parameters to anything other than its default
"g_config.hotpoint_cfg.max_radius_0"

**Comment by mefistotelis** [comment]
Interesting. May be a bug in my script.

**Comment by notsolowki** [comment]
if i change "g_config.hotpoint_cfg.max_radius_0", and then update the aprameters all seems fine, then when i extract the params again i get half the params and this error : Warning: multiple (2) matches found for parameters array with alignment 0x02

**Comment by mefistotelis** [comment]
Please paste your whole definition of this parameter from within JSON file.

**Comment by notsolowki** [comment]
{
		"index" : 463,
		"typeID" : 8,
		"size" : 4,
		"attribute" : 11,
		"minValue" : 100.000000,
		"maxValue" : 500.000000,
		"defaultValue" : 120.000000,
		"name" : "g_config.hotpoint_cfg.max_radius_0",
		"modify" : true
	},

**Comment by notsolowki** [comment]
it appears to be happening when i change some of the max values

**Comment by mefistotelis** [comment]
Found the bug, will fix soon.

**Comment by notsolowki** [comment]
Thankyou!!

**Comment by notsolowki** [comment]
so was it only effecting parameterss with ranges like this or with 'size 4' ?

{
"index" : 463,
"typeID" : 8,
"size" : 4,
"attribute" : 11,
"minValue" : 100.000000,
"maxValue" : 500.000000,
"defaultValue" : 120.000000,
"name" : "g_config.hotpoint_cfg.max_radius_0",
"modify" : true
},

**Comment by notsolowki** [comment]
can you help me solve this speed limit issue im having. it seems that somewhere 10MPS is the max limit for ascend and descend speeds. i know this is not true as far as hardware capability because ive managed to make it takeoff own its own at 60 mph. somewhere in the binary i think theres going to be a parameters with the value 10 thats effecting this. the ascend and descend speeds max out at 22.4MPH which i bet is in the binary as 10MPS somewhere

**Comment by mefistotelis** [comment]
Value of 10.0 is probably very popular in the firmware; it wouldn't be easy to find the correct one.

You may try to replace ALL of them, to make sure the limit is really written somewhere in the firmware as 10.0; but that's quite dangerous - if your flight controller will crash during startup, you may not be able to re-flash it.

**Comment by polarisax** [comment]
Can I use the dji_flyc_param_ed.py script to change the flight parameters in the 1.4.0010 firmware , or it can be only used for the 1.7.0060 fw?

Thanks!

**Comment by polarisax** [comment]
Well...I answer to myself .... this doesn't work!

**Comment by polarisax** [comment]
It seems that there are not encrypted modules in the 1.4 advanced FW.....

$ grep -I "encrypt" -B 2 *.ini
P3S_FW_V01.04.0010_mi00.ini-target=m0305
P3S_FW_V01.04.0010_mi00.ini-version=34.02.0009
P3S_FW_V01.04.0010_mi00.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi00.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi01.ini-target=m0306
P3S_FW_V01.04.0010_mi01.ini-version=02.03.0013
P3S_FW_V01.04.0010_mi01.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi01.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi02.ini-target=m0400
P3S_FW_V01.04.0010_mi02.ini-version=01.41.0000
P3S_FW_V01.04.0010_mi02.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi02.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi03.ini-target=m0900
P3S_FW_V01.04.0010_mi03.ini-version=01.07.0003
P3S_FW_V01.04.0010_mi03.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi04.ini-target=m1100
P3S_FW_V01.04.0010_mi04.ini-version=01.07.0000
P3S_FW_V01.04.0010_mi04.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi05.ini-target=m1200
P3S_FW_V01.04.0010_mi05.ini-version=01.10.0000
P3S_FW_V01.04.0010_mi05.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi05.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi06.ini-target=m1201
P3S_FW_V01.04.0010_mi06.ini-version=01.10.0000
P3S_FW_V01.04.0010_mi06.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi06.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi07.ini-target=m1202
P3S_FW_V01.04.0010_mi07.ini-version=01.10.0000
P3S_FW_V01.04.0010_mi07.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi07.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi08.ini-target=m1203
P3S_FW_V01.04.0010_mi08.ini-version=01.10.0000
P3S_FW_V01.04.0010_mi08.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi08.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi09.ini-target=m1500
P3S_FW_V01.04.0010_mi09.ini-version=01.01.0512
P3S_FW_V01.04.0010_mi09.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi10.ini-target=m1700
P3S_FW_V01.04.0010_mi10.ini-version=01.01.0263
P3S_FW_V01.04.0010_mi10.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi11.ini-target=m1701
P3S_FW_V01.04.0010_mi11.ini-version=01.00.0519
P3S_FW_V01.04.0010_mi11.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi12.ini-target=m1900
P3S_FW_V01.04.0010_mi12.ini-version=01.00.2144
P3S_FW_V01.04.0010_mi12.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi13.ini-target=m0100
P3S_FW_V01.04.0010_mi13.ini-version=01.21.3647
P3S_FW_V01.04.0010_mi13.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi14.ini-target=m0101
P3S_FW_V01.04.0010_mi14.ini-version=01.21.3647
P3S_FW_V01.04.0010_mi14.ini:encrypt_type=0

**Comment by polarisax** [comment]
It seems that there are not encrypted modules in the 1.4 advanced FW.....
### 
$ grep -I "encrypt" -B 2 *.ini
P3S_FW_V01.04.0010_mi00.ini-target=m0305
P3S_FW_V01.04.0010_mi00.ini-version=34.02.0009
P3S_FW_V01.04.0010_mi00.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi00.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi01.ini-target=m0306
P3S_FW_V01.04.0010_mi01.ini-version=02.03.0013
P3S_FW_V01.04.0010_mi01.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi01.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi02.ini-target=m0400
P3S_FW_V01.04.0010_mi02.ini-version=01.41.0000
P3S_FW_V01.04.0010_mi02.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi02.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi03.ini-target=m0900
P3S_FW_V01.04.0010_mi03.ini-version=01.07.0003
P3S_FW_V01.04.0010_mi03.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi04.ini-target=m1100
P3S_FW_V01.04.0010_mi04.ini-version=01.07.0000
P3S_FW_V01.04.0010_mi04.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi05.ini-target=m1200
P3S_FW_V01.04.0010_mi05.ini-version=01.10.0000
P3S_FW_V01.04.0010_mi05.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi05.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi06.ini-target=m1201
P3S_FW_V01.04.0010_mi06.ini-version=01.10.0000
P3S_FW_V01.04.0010_mi06.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi06.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi07.ini-target=m1202
P3S_FW_V01.04.0010_mi07.ini-version=01.10.0000
P3S_FW_V01.04.0010_mi07.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi07.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi08.ini-target=m1203
P3S_FW_V01.04.0010_mi08.ini-version=01.10.0000
P3S_FW_V01.04.0010_mi08.ini:encrypt_type=1
P3S_FW_V01.04.0010_mi08.ini:preencrypted=1
--
P3S_FW_V01.04.0010_mi09.ini-target=m1500
P3S_FW_V01.04.0010_mi09.ini-version=01.01.0512
P3S_FW_V01.04.0010_mi09.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi10.ini-target=m1700
P3S_FW_V01.04.0010_mi10.ini-version=01.01.0263
P3S_FW_V01.04.0010_mi10.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi11.ini-target=m1701
P3S_FW_V01.04.0010_mi11.ini-version=01.00.0519
P3S_FW_V01.04.0010_mi11.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi12.ini-target=m1900
P3S_FW_V01.04.0010_mi12.ini-version=01.00.2144
P3S_FW_V01.04.0010_mi12.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi13.ini-target=m0100
P3S_FW_V01.04.0010_mi13.ini-version=01.21.3647
P3S_FW_V01.04.0010_mi13.ini:encrypt_type=0
--
P3S_FW_V01.04.0010_mi14.ini-target=m0101
P3S_FW_V01.04.0010_mi14.ini-version=01.21.3647
P3S_FW_V01.04.0010_mi14.ini:encrypt_type=0

**Comment by neven385** [comment]
Is there a same version of single module from different firmwares in encrypted and non-encrypted form?

**Comment by mefistotelis** [comment]
We definitely have it for AM603 firmware:
https://mega.nz/#!9MckHaiR!ZwlqwQpPi0j5tgXiJxHQ-e_vHnxNZQtQleXMH9ox4cM

For Phantom firmwares - I didn't checked. You can use "test_all.sh" to download and extract/repack all modules; logs from it can be parsed to check version and encryption of each module.

**Comment by BeeCodiing** [comment]
Is it possible to use the script in P3S's? It looks like all the versions are encrypted :(

**Comment by mefistotelis** [comment]
> It looks like all the versions are encrypted :(

You can check on the wiki - for some modules I listed versions where it's not encrypted. This includes m0306.

**Comment by danieltroger** [comment]
> You can check on the wiki - for some modules I listed versions where it's not encrypted. This includes m0306.

I tried up-and down grading, with debug and without, to 1.7.90, 1.7.84 and 1.5.74. Versions before 1.7.90 brick the gimbal: it says "gimal gyro error" and doesn't move.
Versions before 1.7.94 cause a barometer error and a main controller data error.
Reflashing just m0306 from 1.7.9 on 1.7.94 obviously doesn't help anything either.

@mefistotelis: three questions:
1. how difficult is it to read the unenecrypted firmware from the MC chip with a hardware programmer? Would it be legal to upload it?
2. Can one flash an older m306, from, for example, 1.5.74 to, let's say 1.8.1, without breaking anything?
3. Is it possible to use the other's phantom's m306?

**Comment by mefistotelis** [comment]
> how difficult is it to read the unenecrypted firmware from the MC chip with a hardware programmer? 

Three main situations to handle for this:
1. Maybe the internal flash is protected, maybe not:
[Proprietary code read-out protection on microcontrollers of the STM32F4 Series](http://www.st.com/content/ccc/resource/technical/document/application_note/89/12/c5/e2/0d/0e/45/7f/DM00186528.pdf/files/DM00186528.pdf/jcr:content/translations/en.DM00186528.pdf)
If the protection is disabled:
2. Maybe the FW is written unencrypted on the flash, maybe not.
If the FW is encrypted:
3. Maybe we can read the boot loader and figure out encryption keys

Personally, I don't need FC FW in new version.

> Would it be legal to upload it (unenecrypted firmware from the MC)?

DJI can stop anyone from publishing anything related to their IP. You can get sued even if what you publish is encrypted.

> Can one flash an older m306, from, for example, 1.5.74 to, let's say 1.8.1, without breaking anything?

Maybe. Besides checking version numbers on the wiki, the only way to make sure is to try.

> Is it possible to use the other's phantom's m306?

Depends on what you want to 'use' it for. As long as hardware is the same, FC will work, but may have different expectations on what you connect to it. If you're asking Ph3 Std vs Ph3 Pro - their FC firmwares are binary identical.

**Comment by MrBurnsAT** [comment]
Mefistotelis 

Is I1 Firmware too binary identical?

If yes. It should be possible to flash the unencrypted 1.7 from p3.

**Comment by danieltroger** [comment]
> Personally, I don't need FC FW in new version.

Me neither, if I'd get an old one working... As I said, the gimbal doesn't work and the AC doesn't fly due to a barometer error with the older one's I tried.

> If you're asking Ph3 Std vs Ph3 Pro - their FC firmwares are binary identical.

Yes, I was. That's awesome! So maybe some of those unencrypted work. I'll try P3X_FW_V01.07.0060 and report back.

**Comment by mefistotelis** [comment]
> Is I1 Firmware too binary identical?

Don't know. I didn't look an any Inspire HW or FW.

**Comment by danieltroger** [comment]
Other thing: PMCAPPFw3.bin is the correct filename for only updating the FC on the Ph3 std? So I rename <whatever>_m0306.bin to PMCAPPFw3.bin and just put it on the card ? It doesn't work for me, tried twice. I always need to pack an update containing only m0306.

**Comment by danieltroger** [comment]
> I'll try P3X_FW_V01.07.0060 and report back.

Nope. My p3sta has got some black magic spell upon it.
![picture1](https://user-images.githubusercontent.com/4047180/29490048-9dacb2a0-8530-11e7-8290-b9cb49c17c31.jpg)
![picture2](https://user-images.githubusercontent.com/4047180/29490049-9db2f232-8530-11e7-8d64-51f71ee67120.jpg)

Ideas? Maybe does the developer mode of assistant work with the p3s ? Or I need to get a hardware programmer.

**Comment by mefistotelis** [comment]
Restore settings to default.
Recalibrate barometer.

**Comment by danieltroger** [comment]
> Recalibrate barometer.

Where would I do that?

**Comment by MAVProxyUser** [comment]
@mefistotelis  3. "Maybe we can read the boot loader and figure out encryption keys"
4. maybe someone will leave them laying out for to fork from GitHub (as your right to do so comes from ToS) 

A little bird told me about some forked GitHub repos and a DMCA attempt... you uh... may want to fork this. https://github.com/MAVProxyUser/spray-system/blob/master/app/aes/aes.c#L38

**Comment by notsolowki** [comment]
I want to see this drone go faster. Im not sure how close these esc's and
motors are to running maximum rpm but im willing to risk the destruction
lol. Im suprised more people didnt bring this up. No support for the esc's

**Comment by mefistotelis** [comment]
Since DJI released the encryption keys, we are no longer restricted by firmware versions. Now all versions can be hacked.

**Comment by MAVProxyUser** [comment]
I hope your IDA pro licenses are up to date. ;)
